.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/ApplicationServer.cpp" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/ApplicationServer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Database\&.h'\fP
.br
\fC#include 'Server\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 4 of file ApplicationServer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
