.TH "Database" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Database \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Database\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabase\fP ()"
.br
.ti -1c
.RI "\fB~Database\fP ()"
.br
.ti -1c
.RI "void \fBSendPois\fP (http_request, \fBPoint\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file Database\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Database::Database ()"

.PP
Definition at line 11 of file Database\&.cpp\&.
.SS "Database::~Database ()"

.PP
Definition at line 78 of file Database\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Database::SendPois (http_requestmessage, \fBPoint\fPlocation)"

.PP
Definition at line 15 of file Database\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
