.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/Database.cpp" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/Database.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Database\&.h'\fP
.br
\fC#include 'md5\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <codecvt>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "std::wstring_convert
.br
< std::codecvt_utf8_utf16
.br
< wchar_t > > \fBconverter\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::wstring_convert<std::codecvt_utf8_utf16<wchar_t> > converter"

.PP
Definition at line 9 of file Database\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
