.TH "Point" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Point\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP (float, float, float)"
.br
.ti -1c
.RI "\fB~Point\fP ()"
.br
.ti -1c
.RI "float \fBx\fP ()"
.br
.ti -1c
.RI "float \fBy\fP ()"
.br
.ti -1c
.RI "float \fBz\fP ()"
.br
.ti -1c
.RI "void \fBx\fP (float)"
.br
.ti -1c
.RI "void \fBy\fP (float)"
.br
.ti -1c
.RI "void \fBz\fP (float)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file Point\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Point::Point ()"

.PP
Definition at line 3 of file Point\&.cpp\&.
.SS "Point::Point (floatx = \fC0\fP, floaty = \fC0\fP, floatz = \fC0\fP)"

.PP
Definition at line 12 of file Point\&.cpp\&.
.SS "Point::~Point ()"

.PP
Definition at line 19 of file Point\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "float Point::x ()"

.PP
Definition at line 23 of file Point\&.cpp\&.
.SS "void Point::x (floatx)"

.PP
Definition at line 39 of file Point\&.cpp\&.
.SS "float Point::y ()"

.PP
Definition at line 29 of file Point\&.cpp\&.
.SS "void Point::y (floaty)"

.PP
Definition at line 44 of file Point\&.cpp\&.
.SS "float Point::z ()"

.PP
Definition at line 34 of file Point\&.cpp\&.
.SS "void Point::z (floatz)"

.PP
Definition at line 49 of file Point\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
