.TH "Server" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Server \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServer\fP (const http::uri &url)"
.br
.ti -1c
.RI "pplx::task< void > \fBopen\fP ()"
.br
.ti -1c
.RI "pplx::task< void > \fBclose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Server\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Server::Server (const http::uri &url)"

.PP
Definition at line 10 of file Server\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "pplx::task<void> Server::close ()\fC [inline]\fP"

.PP
Definition at line 14 of file Server\&.h\&.
.SS "pplx::task<void> Server::open ()\fC [inline]\fP"

.PP
Definition at line 13 of file Server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
