.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/Server.h" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/Server.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cpprest\\http_listener\&.h>\fP
.br
\fC#include 'Users\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBServer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
