.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/Server.cpp" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/Server.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Server\&.h'\fP
.br
\fC#include 'Database\&.h'\fP
.br
\fC#include <random>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDatabase\fP \fBPOIsDb\fP"
.br
.ti -1c
.RI "\fBUsers\fP \fBclientsDb\fP"
.br
.ti -1c
.RI "int \fBpower\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBUsers\fP clientsDb"

.PP
Definition at line 7 of file Server\&.cpp\&.
.SS "\fBDatabase\fP POIsDb"

.PP
Definition at line 6 of file Server\&.cpp\&.
.SS "int power"

.PP
Definition at line 8 of file Server\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
