.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/targetver.h" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/targetver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <SDKDDKVer\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
