.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/Users.h" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/Users.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'User\&.h'\fP
.br
\fC#include 'md5\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUsers\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_USE_MATH_DEFINES\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef map< utility::string_t, 
.br
\fBUser\fP * > \fBListOfClients\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _USE_MATH_DEFINES"

.PP
Definition at line 5 of file Users\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef map<utility::string_t, \fBUser\fP*> \fBListOfClients\fP"

.PP
Definition at line 9 of file Users\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
