.TH "J:/Eevee/application server/ApplicationServer/ApplicationServer/Users.cpp" 3 "Wed Oct 8 2014" "Application Server" \" -*- nroff -*-
.ad l
.nh
.SH NAME
J:/Eevee/application server/ApplicationServer/ApplicationServer/Users.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Users\&.h'\fP
.br
\fC#include <codecvt>\fP
.br
\fC#include <cstring>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "std::wstring_convert
.br
< std::codecvt_utf8_utf16
.br
< wchar_t > > \fBstrconverter\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::wstring_convert<std::codecvt_utf8_utf16<wchar_t> > strconverter"

.PP
Definition at line 7 of file Users\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Application Server from the source code\&.
